name: 查询股票信息
on:
  schedule:
    - cron: "50 8 * * 1-5"
    - cron: "52 2 * * 1-5"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Execute
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
        run: node scripts/notify-stock.js
